# CMAKE generated file: DO NOT EDIT!
# Generated by "MinGW Makefiles" Generator, CMake Version 4.2

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

SHELL = cmd.exe

# The CMake executable.
CMAKE_COMMAND = "C:\Program Files\CMake\bin\cmake.exe"

# The command to remove a file.
RM = "C:\Program Files\CMake\bin\cmake.exe" -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = D:\Development\nyanners\ceng

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = D:\Development\nyanners\ceng

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target package
package: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Run CPack packaging tool..."
	"C:\Program Files\CMake\bin\cpack.exe" --config ./CPackConfig.cmake
.PHONY : package

# Special rule for the target package
package/fast: package
.PHONY : package/fast

# Special rule for the target package_source
package_source:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Run CPack packaging tool for source..."
	"C:\Program Files\CMake\bin\cpack.exe" --config ./CPackSourceConfig.cmake
.PHONY : package_source

# Special rule for the target package_source
package_source/fast: package_source
.PHONY : package_source/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	"C:\Program Files\CMake\bin\cmake-gui.exe" -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	"C:\Program Files\CMake\bin\cmake.exe" --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	"C:\Program Files\CMake\bin\cmake.exe" -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	"C:\Program Files\CMake\bin\cmake.exe" -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	"C:\Program Files\CMake\bin\cmake.exe" -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	"C:\Program Files\CMake\bin\cmake.exe" -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	"C:\Program Files\CMake\bin\cmake.exe" -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	"C:\Program Files\CMake\bin\cmake.exe" -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start D:\Development\nyanners\ceng\CMakeFiles D:\Development\nyanners\ceng\\CMakeFiles\progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start D:\Development\nyanners\ceng\CMakeFiles 0
.PHONY : all

# The main codegen target
codegen: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start D:\Development\nyanners\ceng\CMakeFiles D:\Development\nyanners\ceng\\CMakeFiles\progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 codegen
	$(CMAKE_COMMAND) -E cmake_progress_start D:\Development\nyanners\ceng\CMakeFiles 0
.PHONY : codegen

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Nyanners

# Build rule for target.
Nyanners: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 Nyanners
.PHONY : Nyanners

# fast build rule for target.
Nyanners/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Nyanners.dir\build.make CMakeFiles/Nyanners.dir/build
.PHONY : Nyanners/fast

#=============================================================================
# Target rules for targets named Luau.Common

# Build rule for target.
Luau.Common: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 Luau.Common
.PHONY : Luau.Common

# fast build rule for target.
Luau.Common/fast:
	$(MAKE) $(MAKESILENT) -f vendor\libs\luau\CMakeFiles\Luau.Common.dir\build.make vendor/libs/luau/CMakeFiles/Luau.Common.dir/build
.PHONY : Luau.Common/fast

#=============================================================================
# Target rules for targets named Luau.CLI.lib

# Build rule for target.
Luau.CLI.lib: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 Luau.CLI.lib
.PHONY : Luau.CLI.lib

# fast build rule for target.
Luau.CLI.lib/fast:
	$(MAKE) $(MAKESILENT) -f vendor\libs\luau\CMakeFiles\Luau.CLI.lib.dir\build.make vendor/libs/luau/CMakeFiles/Luau.CLI.lib.dir/build
.PHONY : Luau.CLI.lib/fast

#=============================================================================
# Target rules for targets named Luau.Ast

# Build rule for target.
Luau.Ast: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 Luau.Ast
.PHONY : Luau.Ast

# fast build rule for target.
Luau.Ast/fast:
	$(MAKE) $(MAKESILENT) -f vendor\libs\luau\CMakeFiles\Luau.Ast.dir\build.make vendor/libs/luau/CMakeFiles/Luau.Ast.dir/build
.PHONY : Luau.Ast/fast

#=============================================================================
# Target rules for targets named Luau.Compiler

# Build rule for target.
Luau.Compiler: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 Luau.Compiler
.PHONY : Luau.Compiler

# fast build rule for target.
Luau.Compiler/fast:
	$(MAKE) $(MAKESILENT) -f vendor\libs\luau\CMakeFiles\Luau.Compiler.dir\build.make vendor/libs/luau/CMakeFiles/Luau.Compiler.dir/build
.PHONY : Luau.Compiler/fast

#=============================================================================
# Target rules for targets named Luau.Config

# Build rule for target.
Luau.Config: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 Luau.Config
.PHONY : Luau.Config

# fast build rule for target.
Luau.Config/fast:
	$(MAKE) $(MAKESILENT) -f vendor\libs\luau\CMakeFiles\Luau.Config.dir\build.make vendor/libs/luau/CMakeFiles/Luau.Config.dir/build
.PHONY : Luau.Config/fast

#=============================================================================
# Target rules for targets named Luau.Analysis

# Build rule for target.
Luau.Analysis: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 Luau.Analysis
.PHONY : Luau.Analysis

# fast build rule for target.
Luau.Analysis/fast:
	$(MAKE) $(MAKESILENT) -f vendor\libs\luau\CMakeFiles\Luau.Analysis.dir\build.make vendor/libs/luau/CMakeFiles/Luau.Analysis.dir/build
.PHONY : Luau.Analysis/fast

#=============================================================================
# Target rules for targets named Luau.EqSat

# Build rule for target.
Luau.EqSat: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 Luau.EqSat
.PHONY : Luau.EqSat

# fast build rule for target.
Luau.EqSat/fast:
	$(MAKE) $(MAKESILENT) -f vendor\libs\luau\CMakeFiles\Luau.EqSat.dir\build.make vendor/libs/luau/CMakeFiles/Luau.EqSat.dir/build
.PHONY : Luau.EqSat/fast

#=============================================================================
# Target rules for targets named Luau.CodeGen

# Build rule for target.
Luau.CodeGen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 Luau.CodeGen
.PHONY : Luau.CodeGen

# fast build rule for target.
Luau.CodeGen/fast:
	$(MAKE) $(MAKESILENT) -f vendor\libs\luau\CMakeFiles\Luau.CodeGen.dir\build.make vendor/libs/luau/CMakeFiles/Luau.CodeGen.dir/build
.PHONY : Luau.CodeGen/fast

#=============================================================================
# Target rules for targets named Luau.VM

# Build rule for target.
Luau.VM: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 Luau.VM
.PHONY : Luau.VM

# fast build rule for target.
Luau.VM/fast:
	$(MAKE) $(MAKESILENT) -f vendor\libs\luau\CMakeFiles\Luau.VM.dir\build.make vendor/libs/luau/CMakeFiles/Luau.VM.dir/build
.PHONY : Luau.VM/fast

#=============================================================================
# Target rules for targets named Luau.Require

# Build rule for target.
Luau.Require: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 Luau.Require
.PHONY : Luau.Require

# fast build rule for target.
Luau.Require/fast:
	$(MAKE) $(MAKESILENT) -f vendor\libs\luau\CMakeFiles\Luau.Require.dir\build.make vendor/libs/luau/CMakeFiles/Luau.Require.dir/build
.PHONY : Luau.Require/fast

#=============================================================================
# Target rules for targets named Luau.RequireNavigator

# Build rule for target.
Luau.RequireNavigator: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 Luau.RequireNavigator
.PHONY : Luau.RequireNavigator

# fast build rule for target.
Luau.RequireNavigator/fast:
	$(MAKE) $(MAKESILENT) -f vendor\libs\luau\CMakeFiles\Luau.RequireNavigator.dir\build.make vendor/libs/luau/CMakeFiles/Luau.RequireNavigator.dir/build
.PHONY : Luau.RequireNavigator/fast

#=============================================================================
# Target rules for targets named isocline

# Build rule for target.
isocline: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 isocline
.PHONY : isocline

# fast build rule for target.
isocline/fast:
	$(MAKE) $(MAKESILENT) -f vendor\libs\luau\CMakeFiles\isocline.dir\build.make vendor/libs/luau/CMakeFiles/isocline.dir/build
.PHONY : isocline/fast

#=============================================================================
# Target rules for targets named Luau.Repl.CLI

# Build rule for target.
Luau.Repl.CLI: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 Luau.Repl.CLI
.PHONY : Luau.Repl.CLI

# fast build rule for target.
Luau.Repl.CLI/fast:
	$(MAKE) $(MAKESILENT) -f vendor\libs\luau\CMakeFiles\Luau.Repl.CLI.dir\build.make vendor/libs/luau/CMakeFiles/Luau.Repl.CLI.dir/build
.PHONY : Luau.Repl.CLI/fast

#=============================================================================
# Target rules for targets named Luau.Analyze.CLI

# Build rule for target.
Luau.Analyze.CLI: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 Luau.Analyze.CLI
.PHONY : Luau.Analyze.CLI

# fast build rule for target.
Luau.Analyze.CLI/fast:
	$(MAKE) $(MAKESILENT) -f vendor\libs\luau\CMakeFiles\Luau.Analyze.CLI.dir\build.make vendor/libs/luau/CMakeFiles/Luau.Analyze.CLI.dir/build
.PHONY : Luau.Analyze.CLI/fast

#=============================================================================
# Target rules for targets named Luau.Ast.CLI

# Build rule for target.
Luau.Ast.CLI: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 Luau.Ast.CLI
.PHONY : Luau.Ast.CLI

# fast build rule for target.
Luau.Ast.CLI/fast:
	$(MAKE) $(MAKESILENT) -f vendor\libs\luau\CMakeFiles\Luau.Ast.CLI.dir\build.make vendor/libs/luau/CMakeFiles/Luau.Ast.CLI.dir/build
.PHONY : Luau.Ast.CLI/fast

#=============================================================================
# Target rules for targets named Luau.Reduce.CLI

# Build rule for target.
Luau.Reduce.CLI: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 Luau.Reduce.CLI
.PHONY : Luau.Reduce.CLI

# fast build rule for target.
Luau.Reduce.CLI/fast:
	$(MAKE) $(MAKESILENT) -f vendor\libs\luau\CMakeFiles\Luau.Reduce.CLI.dir\build.make vendor/libs/luau/CMakeFiles/Luau.Reduce.CLI.dir/build
.PHONY : Luau.Reduce.CLI/fast

#=============================================================================
# Target rules for targets named Luau.Compile.CLI

# Build rule for target.
Luau.Compile.CLI: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 Luau.Compile.CLI
.PHONY : Luau.Compile.CLI

# fast build rule for target.
Luau.Compile.CLI/fast:
	$(MAKE) $(MAKESILENT) -f vendor\libs\luau\CMakeFiles\Luau.Compile.CLI.dir\build.make vendor/libs/luau/CMakeFiles/Luau.Compile.CLI.dir/build
.PHONY : Luau.Compile.CLI/fast

#=============================================================================
# Target rules for targets named Luau.Bytecode.CLI

# Build rule for target.
Luau.Bytecode.CLI: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 Luau.Bytecode.CLI
.PHONY : Luau.Bytecode.CLI

# fast build rule for target.
Luau.Bytecode.CLI/fast:
	$(MAKE) $(MAKESILENT) -f vendor\libs\luau\CMakeFiles\Luau.Bytecode.CLI.dir\build.make vendor/libs/luau/CMakeFiles/Luau.Bytecode.CLI.dir/build
.PHONY : Luau.Bytecode.CLI/fast

#=============================================================================
# Target rules for targets named Luau.UnitTest

# Build rule for target.
Luau.UnitTest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 Luau.UnitTest
.PHONY : Luau.UnitTest

# fast build rule for target.
Luau.UnitTest/fast:
	$(MAKE) $(MAKESILENT) -f vendor\libs\luau\CMakeFiles\Luau.UnitTest.dir\build.make vendor/libs/luau/CMakeFiles/Luau.UnitTest.dir/build
.PHONY : Luau.UnitTest/fast

#=============================================================================
# Target rules for targets named Luau.Conformance

# Build rule for target.
Luau.Conformance: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 Luau.Conformance
.PHONY : Luau.Conformance

# fast build rule for target.
Luau.Conformance/fast:
	$(MAKE) $(MAKESILENT) -f vendor\libs\luau\CMakeFiles\Luau.Conformance.dir\build.make vendor/libs/luau/CMakeFiles/Luau.Conformance.dir/build
.PHONY : Luau.Conformance/fast

#=============================================================================
# Target rules for targets named Luau.CLI.Test

# Build rule for target.
Luau.CLI.Test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 Luau.CLI.Test
.PHONY : Luau.CLI.Test

# fast build rule for target.
Luau.CLI.Test/fast:
	$(MAKE) $(MAKESILENT) -f vendor\libs\luau\CMakeFiles\Luau.CLI.Test.dir\build.make vendor/libs/luau/CMakeFiles/Luau.CLI.Test.dir/build
.PHONY : Luau.CLI.Test/fast

#=============================================================================
# Target rules for targets named uninstall

# Build rule for target.
uninstall: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 uninstall
.PHONY : uninstall

# fast build rule for target.
uninstall/fast:
	$(MAKE) $(MAKESILENT) -f vendor\libs\raylib\CMakeFiles\uninstall.dir\build.make vendor/libs/raylib/CMakeFiles/uninstall.dir/build
.PHONY : uninstall/fast

#=============================================================================
# Target rules for targets named raylib

# Build rule for target.
raylib: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 raylib
.PHONY : raylib

# fast build rule for target.
raylib/fast:
	$(MAKE) $(MAKESILENT) -f vendor\libs\raylib\raylib\CMakeFiles\raylib.dir\build.make vendor/libs/raylib/raylib/CMakeFiles/raylib.dir/build
.PHONY : raylib/fast

#=============================================================================
# Target rules for targets named glfw

# Build rule for target.
glfw: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 glfw
.PHONY : glfw

# fast build rule for target.
glfw/fast:
	$(MAKE) $(MAKESILENT) -f vendor\libs\raylib\raylib\external\glfw\src\CMakeFiles\glfw.dir\build.make vendor/libs/raylib/raylib/external/glfw/src/CMakeFiles/glfw.dir/build
.PHONY : glfw/fast

#=============================================================================
# Target rules for targets named update_mappings

# Build rule for target.
update_mappings: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 update_mappings
.PHONY : update_mappings

# fast build rule for target.
update_mappings/fast:
	$(MAKE) $(MAKESILENT) -f vendor\libs\raylib\raylib\external\glfw\src\CMakeFiles\update_mappings.dir\build.make vendor/libs/raylib/raylib/external/glfw/src/CMakeFiles/update_mappings.dir/build
.PHONY : update_mappings/fast

engine/engine.obj: engine/engine.cpp.obj
.PHONY : engine/engine.obj

# target to build an object file
engine/engine.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Nyanners.dir\build.make CMakeFiles/Nyanners.dir/engine/engine.cpp.obj
.PHONY : engine/engine.cpp.obj

engine/engine.i: engine/engine.cpp.i
.PHONY : engine/engine.i

# target to preprocess a source file
engine/engine.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Nyanners.dir\build.make CMakeFiles/Nyanners.dir/engine/engine.cpp.i
.PHONY : engine/engine.cpp.i

engine/engine.s: engine/engine.cpp.s
.PHONY : engine/engine.s

# target to generate assembly for a file
engine/engine.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Nyanners.dir\build.make CMakeFiles/Nyanners.dir/engine/engine.cpp.s
.PHONY : engine/engine.cpp.s

# Help Target
help:
	@echo The following are some of the valid targets for this Makefile:
	@echo ... all (the default if no target is provided)
	@echo ... clean
	@echo ... depend
	@echo ... codegen
	@echo ... edit_cache
	@echo ... install
	@echo ... install/local
	@echo ... install/strip
	@echo ... list_install_components
	@echo ... package
	@echo ... package_source
	@echo ... rebuild_cache
	@echo ... uninstall
	@echo ... update_mappings
	@echo ... Luau.Analysis
	@echo ... Luau.Analyze.CLI
	@echo ... Luau.Ast
	@echo ... Luau.Ast.CLI
	@echo ... Luau.Bytecode.CLI
	@echo ... Luau.CLI.Test
	@echo ... Luau.CLI.lib
	@echo ... Luau.CodeGen
	@echo ... Luau.Common
	@echo ... Luau.Compile.CLI
	@echo ... Luau.Compiler
	@echo ... Luau.Config
	@echo ... Luau.Conformance
	@echo ... Luau.EqSat
	@echo ... Luau.Reduce.CLI
	@echo ... Luau.Repl.CLI
	@echo ... Luau.Require
	@echo ... Luau.RequireNavigator
	@echo ... Luau.UnitTest
	@echo ... Luau.VM
	@echo ... Nyanners
	@echo ... glfw
	@echo ... isocline
	@echo ... raylib
	@echo ... engine/engine.obj
	@echo ... engine/engine.i
	@echo ... engine/engine.s
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 0
.PHONY : cmake_check_build_system

