# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.1

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /mnt/airi/Development/nyanners/ceng

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /mnt/airi/Development/nyanners/ceng

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target package
package: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Run CPack packaging tool..."
	/usr/bin/cpack --config ./CPackConfig.cmake
.PHONY : package

# Special rule for the target package
package/fast: package
.PHONY : package/fast

# Special rule for the target package_source
package_source:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Run CPack packaging tool for source..."
	/usr/bin/cpack --config ./CPackSourceConfig.cmake /mnt/airi/Development/nyanners/ceng/CPackSourceConfig.cmake
.PHONY : package_source

# Special rule for the target package_source
package_source/fast: package_source
.PHONY : package_source/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/airi/Development/nyanners/ceng/CMakeFiles /mnt/airi/Development/nyanners/ceng//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/airi/Development/nyanners/ceng/CMakeFiles 0
.PHONY : all

# The main codegen target
codegen: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/airi/Development/nyanners/ceng/CMakeFiles /mnt/airi/Development/nyanners/ceng//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 codegen
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/airi/Development/nyanners/ceng/CMakeFiles 0
.PHONY : codegen

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Nyanners

# Build rule for target.
Nyanners: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Nyanners
.PHONY : Nyanners

# fast build rule for target.
Nyanners/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Nyanners.dir/build.make CMakeFiles/Nyanners.dir/build
.PHONY : Nyanners/fast

#=============================================================================
# Target rules for targets named Luau.Common

# Build rule for target.
Luau.Common: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Luau.Common
.PHONY : Luau.Common

# fast build rule for target.
Luau.Common/fast:
	$(MAKE) $(MAKESILENT) -f vendor/libs/luau/CMakeFiles/Luau.Common.dir/build.make vendor/libs/luau/CMakeFiles/Luau.Common.dir/build
.PHONY : Luau.Common/fast

#=============================================================================
# Target rules for targets named Luau.CLI.lib

# Build rule for target.
Luau.CLI.lib: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Luau.CLI.lib
.PHONY : Luau.CLI.lib

# fast build rule for target.
Luau.CLI.lib/fast:
	$(MAKE) $(MAKESILENT) -f vendor/libs/luau/CMakeFiles/Luau.CLI.lib.dir/build.make vendor/libs/luau/CMakeFiles/Luau.CLI.lib.dir/build
.PHONY : Luau.CLI.lib/fast

#=============================================================================
# Target rules for targets named Luau.Ast

# Build rule for target.
Luau.Ast: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Luau.Ast
.PHONY : Luau.Ast

# fast build rule for target.
Luau.Ast/fast:
	$(MAKE) $(MAKESILENT) -f vendor/libs/luau/CMakeFiles/Luau.Ast.dir/build.make vendor/libs/luau/CMakeFiles/Luau.Ast.dir/build
.PHONY : Luau.Ast/fast

#=============================================================================
# Target rules for targets named Luau.Compiler

# Build rule for target.
Luau.Compiler: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Luau.Compiler
.PHONY : Luau.Compiler

# fast build rule for target.
Luau.Compiler/fast:
	$(MAKE) $(MAKESILENT) -f vendor/libs/luau/CMakeFiles/Luau.Compiler.dir/build.make vendor/libs/luau/CMakeFiles/Luau.Compiler.dir/build
.PHONY : Luau.Compiler/fast

#=============================================================================
# Target rules for targets named Luau.Config

# Build rule for target.
Luau.Config: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Luau.Config
.PHONY : Luau.Config

# fast build rule for target.
Luau.Config/fast:
	$(MAKE) $(MAKESILENT) -f vendor/libs/luau/CMakeFiles/Luau.Config.dir/build.make vendor/libs/luau/CMakeFiles/Luau.Config.dir/build
.PHONY : Luau.Config/fast

#=============================================================================
# Target rules for targets named Luau.Analysis

# Build rule for target.
Luau.Analysis: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Luau.Analysis
.PHONY : Luau.Analysis

# fast build rule for target.
Luau.Analysis/fast:
	$(MAKE) $(MAKESILENT) -f vendor/libs/luau/CMakeFiles/Luau.Analysis.dir/build.make vendor/libs/luau/CMakeFiles/Luau.Analysis.dir/build
.PHONY : Luau.Analysis/fast

#=============================================================================
# Target rules for targets named Luau.EqSat

# Build rule for target.
Luau.EqSat: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Luau.EqSat
.PHONY : Luau.EqSat

# fast build rule for target.
Luau.EqSat/fast:
	$(MAKE) $(MAKESILENT) -f vendor/libs/luau/CMakeFiles/Luau.EqSat.dir/build.make vendor/libs/luau/CMakeFiles/Luau.EqSat.dir/build
.PHONY : Luau.EqSat/fast

#=============================================================================
# Target rules for targets named Luau.CodeGen

# Build rule for target.
Luau.CodeGen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Luau.CodeGen
.PHONY : Luau.CodeGen

# fast build rule for target.
Luau.CodeGen/fast:
	$(MAKE) $(MAKESILENT) -f vendor/libs/luau/CMakeFiles/Luau.CodeGen.dir/build.make vendor/libs/luau/CMakeFiles/Luau.CodeGen.dir/build
.PHONY : Luau.CodeGen/fast

#=============================================================================
# Target rules for targets named Luau.VM

# Build rule for target.
Luau.VM: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Luau.VM
.PHONY : Luau.VM

# fast build rule for target.
Luau.VM/fast:
	$(MAKE) $(MAKESILENT) -f vendor/libs/luau/CMakeFiles/Luau.VM.dir/build.make vendor/libs/luau/CMakeFiles/Luau.VM.dir/build
.PHONY : Luau.VM/fast

#=============================================================================
# Target rules for targets named Luau.Require

# Build rule for target.
Luau.Require: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Luau.Require
.PHONY : Luau.Require

# fast build rule for target.
Luau.Require/fast:
	$(MAKE) $(MAKESILENT) -f vendor/libs/luau/CMakeFiles/Luau.Require.dir/build.make vendor/libs/luau/CMakeFiles/Luau.Require.dir/build
.PHONY : Luau.Require/fast

#=============================================================================
# Target rules for targets named Luau.RequireNavigator

# Build rule for target.
Luau.RequireNavigator: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Luau.RequireNavigator
.PHONY : Luau.RequireNavigator

# fast build rule for target.
Luau.RequireNavigator/fast:
	$(MAKE) $(MAKESILENT) -f vendor/libs/luau/CMakeFiles/Luau.RequireNavigator.dir/build.make vendor/libs/luau/CMakeFiles/Luau.RequireNavigator.dir/build
.PHONY : Luau.RequireNavigator/fast

#=============================================================================
# Target rules for targets named isocline

# Build rule for target.
isocline: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 isocline
.PHONY : isocline

# fast build rule for target.
isocline/fast:
	$(MAKE) $(MAKESILENT) -f vendor/libs/luau/CMakeFiles/isocline.dir/build.make vendor/libs/luau/CMakeFiles/isocline.dir/build
.PHONY : isocline/fast

#=============================================================================
# Target rules for targets named Luau.Repl.CLI

# Build rule for target.
Luau.Repl.CLI: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Luau.Repl.CLI
.PHONY : Luau.Repl.CLI

# fast build rule for target.
Luau.Repl.CLI/fast:
	$(MAKE) $(MAKESILENT) -f vendor/libs/luau/CMakeFiles/Luau.Repl.CLI.dir/build.make vendor/libs/luau/CMakeFiles/Luau.Repl.CLI.dir/build
.PHONY : Luau.Repl.CLI/fast

#=============================================================================
# Target rules for targets named Luau.Analyze.CLI

# Build rule for target.
Luau.Analyze.CLI: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Luau.Analyze.CLI
.PHONY : Luau.Analyze.CLI

# fast build rule for target.
Luau.Analyze.CLI/fast:
	$(MAKE) $(MAKESILENT) -f vendor/libs/luau/CMakeFiles/Luau.Analyze.CLI.dir/build.make vendor/libs/luau/CMakeFiles/Luau.Analyze.CLI.dir/build
.PHONY : Luau.Analyze.CLI/fast

#=============================================================================
# Target rules for targets named Luau.Ast.CLI

# Build rule for target.
Luau.Ast.CLI: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Luau.Ast.CLI
.PHONY : Luau.Ast.CLI

# fast build rule for target.
Luau.Ast.CLI/fast:
	$(MAKE) $(MAKESILENT) -f vendor/libs/luau/CMakeFiles/Luau.Ast.CLI.dir/build.make vendor/libs/luau/CMakeFiles/Luau.Ast.CLI.dir/build
.PHONY : Luau.Ast.CLI/fast

#=============================================================================
# Target rules for targets named Luau.Reduce.CLI

# Build rule for target.
Luau.Reduce.CLI: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Luau.Reduce.CLI
.PHONY : Luau.Reduce.CLI

# fast build rule for target.
Luau.Reduce.CLI/fast:
	$(MAKE) $(MAKESILENT) -f vendor/libs/luau/CMakeFiles/Luau.Reduce.CLI.dir/build.make vendor/libs/luau/CMakeFiles/Luau.Reduce.CLI.dir/build
.PHONY : Luau.Reduce.CLI/fast

#=============================================================================
# Target rules for targets named Luau.Compile.CLI

# Build rule for target.
Luau.Compile.CLI: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Luau.Compile.CLI
.PHONY : Luau.Compile.CLI

# fast build rule for target.
Luau.Compile.CLI/fast:
	$(MAKE) $(MAKESILENT) -f vendor/libs/luau/CMakeFiles/Luau.Compile.CLI.dir/build.make vendor/libs/luau/CMakeFiles/Luau.Compile.CLI.dir/build
.PHONY : Luau.Compile.CLI/fast

#=============================================================================
# Target rules for targets named Luau.Bytecode.CLI

# Build rule for target.
Luau.Bytecode.CLI: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Luau.Bytecode.CLI
.PHONY : Luau.Bytecode.CLI

# fast build rule for target.
Luau.Bytecode.CLI/fast:
	$(MAKE) $(MAKESILENT) -f vendor/libs/luau/CMakeFiles/Luau.Bytecode.CLI.dir/build.make vendor/libs/luau/CMakeFiles/Luau.Bytecode.CLI.dir/build
.PHONY : Luau.Bytecode.CLI/fast

#=============================================================================
# Target rules for targets named Luau.UnitTest

# Build rule for target.
Luau.UnitTest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Luau.UnitTest
.PHONY : Luau.UnitTest

# fast build rule for target.
Luau.UnitTest/fast:
	$(MAKE) $(MAKESILENT) -f vendor/libs/luau/CMakeFiles/Luau.UnitTest.dir/build.make vendor/libs/luau/CMakeFiles/Luau.UnitTest.dir/build
.PHONY : Luau.UnitTest/fast

#=============================================================================
# Target rules for targets named Luau.Conformance

# Build rule for target.
Luau.Conformance: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Luau.Conformance
.PHONY : Luau.Conformance

# fast build rule for target.
Luau.Conformance/fast:
	$(MAKE) $(MAKESILENT) -f vendor/libs/luau/CMakeFiles/Luau.Conformance.dir/build.make vendor/libs/luau/CMakeFiles/Luau.Conformance.dir/build
.PHONY : Luau.Conformance/fast

#=============================================================================
# Target rules for targets named Luau.CLI.Test

# Build rule for target.
Luau.CLI.Test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Luau.CLI.Test
.PHONY : Luau.CLI.Test

# fast build rule for target.
Luau.CLI.Test/fast:
	$(MAKE) $(MAKESILENT) -f vendor/libs/luau/CMakeFiles/Luau.CLI.Test.dir/build.make vendor/libs/luau/CMakeFiles/Luau.CLI.Test.dir/build
.PHONY : Luau.CLI.Test/fast

#=============================================================================
# Target rules for targets named raylib

# Build rule for target.
raylib: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 raylib
.PHONY : raylib

# fast build rule for target.
raylib/fast:
	$(MAKE) $(MAKESILENT) -f vendor/libs/raylib/raylib/CMakeFiles/raylib.dir/build.make vendor/libs/raylib/raylib/CMakeFiles/raylib.dir/build
.PHONY : raylib/fast

#=============================================================================
# Target rules for targets named glfw

# Build rule for target.
glfw: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 glfw
.PHONY : glfw

# fast build rule for target.
glfw/fast:
	$(MAKE) $(MAKESILENT) -f vendor/libs/raylib/raylib/external/glfw/src/CMakeFiles/glfw.dir/build.make vendor/libs/raylib/raylib/external/glfw/src/CMakeFiles/glfw.dir/build
.PHONY : glfw/fast

#=============================================================================
# Target rules for targets named update_mappings

# Build rule for target.
update_mappings: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 update_mappings
.PHONY : update_mappings

# fast build rule for target.
update_mappings/fast:
	$(MAKE) $(MAKESILENT) -f vendor/libs/raylib/raylib/external/glfw/src/CMakeFiles/update_mappings.dir/build.make vendor/libs/raylib/raylib/external/glfw/src/CMakeFiles/update_mappings.dir/build
.PHONY : update_mappings/fast

engine/instances/DataModel.o: engine/instances/DataModel.cpp.o
.PHONY : engine/instances/DataModel.o

# target to build an object file
engine/instances/DataModel.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Nyanners.dir/build.make CMakeFiles/Nyanners.dir/engine/instances/DataModel.cpp.o
.PHONY : engine/instances/DataModel.cpp.o

engine/instances/DataModel.i: engine/instances/DataModel.cpp.i
.PHONY : engine/instances/DataModel.i

# target to preprocess a source file
engine/instances/DataModel.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Nyanners.dir/build.make CMakeFiles/Nyanners.dir/engine/instances/DataModel.cpp.i
.PHONY : engine/instances/DataModel.cpp.i

engine/instances/DataModel.s: engine/instances/DataModel.cpp.s
.PHONY : engine/instances/DataModel.s

# target to generate assembly for a file
engine/instances/DataModel.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Nyanners.dir/build.make CMakeFiles/Nyanners.dir/engine/instances/DataModel.cpp.s
.PHONY : engine/instances/DataModel.cpp.s

engine/instances/Instance.o: engine/instances/Instance.cpp.o
.PHONY : engine/instances/Instance.o

# target to build an object file
engine/instances/Instance.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Nyanners.dir/build.make CMakeFiles/Nyanners.dir/engine/instances/Instance.cpp.o
.PHONY : engine/instances/Instance.cpp.o

engine/instances/Instance.i: engine/instances/Instance.cpp.i
.PHONY : engine/instances/Instance.i

# target to preprocess a source file
engine/instances/Instance.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Nyanners.dir/build.make CMakeFiles/Nyanners.dir/engine/instances/Instance.cpp.i
.PHONY : engine/instances/Instance.cpp.i

engine/instances/Instance.s: engine/instances/Instance.cpp.s
.PHONY : engine/instances/Instance.s

# target to generate assembly for a file
engine/instances/Instance.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Nyanners.dir/build.make CMakeFiles/Nyanners.dir/engine/instances/Instance.cpp.s
.PHONY : engine/instances/Instance.cpp.s

engine/instances/Script.o: engine/instances/Script.cpp.o
.PHONY : engine/instances/Script.o

# target to build an object file
engine/instances/Script.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Nyanners.dir/build.make CMakeFiles/Nyanners.dir/engine/instances/Script.cpp.o
.PHONY : engine/instances/Script.cpp.o

engine/instances/Script.i: engine/instances/Script.cpp.i
.PHONY : engine/instances/Script.i

# target to preprocess a source file
engine/instances/Script.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Nyanners.dir/build.make CMakeFiles/Nyanners.dir/engine/instances/Script.cpp.i
.PHONY : engine/instances/Script.cpp.i

engine/instances/Script.s: engine/instances/Script.cpp.s
.PHONY : engine/instances/Script.s

# target to generate assembly for a file
engine/instances/Script.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Nyanners.dir/build.make CMakeFiles/Nyanners.dir/engine/instances/Script.cpp.s
.PHONY : engine/instances/Script.cpp.s

engine/lua/system.o: engine/lua/system.cpp.o
.PHONY : engine/lua/system.o

# target to build an object file
engine/lua/system.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Nyanners.dir/build.make CMakeFiles/Nyanners.dir/engine/lua/system.cpp.o
.PHONY : engine/lua/system.cpp.o

engine/lua/system.i: engine/lua/system.cpp.i
.PHONY : engine/lua/system.i

# target to preprocess a source file
engine/lua/system.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Nyanners.dir/build.make CMakeFiles/Nyanners.dir/engine/lua/system.cpp.i
.PHONY : engine/lua/system.cpp.i

engine/lua/system.s: engine/lua/system.cpp.s
.PHONY : engine/lua/system.s

# target to generate assembly for a file
engine/lua/system.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Nyanners.dir/build.make CMakeFiles/Nyanners.dir/engine/lua/system.cpp.s
.PHONY : engine/lua/system.cpp.s

engine/lua/utils.o: engine/lua/utils.cpp.o
.PHONY : engine/lua/utils.o

# target to build an object file
engine/lua/utils.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Nyanners.dir/build.make CMakeFiles/Nyanners.dir/engine/lua/utils.cpp.o
.PHONY : engine/lua/utils.cpp.o

engine/lua/utils.i: engine/lua/utils.cpp.i
.PHONY : engine/lua/utils.i

# target to preprocess a source file
engine/lua/utils.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Nyanners.dir/build.make CMakeFiles/Nyanners.dir/engine/lua/utils.cpp.i
.PHONY : engine/lua/utils.cpp.i

engine/lua/utils.s: engine/lua/utils.cpp.s
.PHONY : engine/lua/utils.s

# target to generate assembly for a file
engine/lua/utils.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Nyanners.dir/build.make CMakeFiles/Nyanners.dir/engine/lua/utils.cpp.s
.PHONY : engine/lua/utils.cpp.s

engine/main.o: engine/main.cpp.o
.PHONY : engine/main.o

# target to build an object file
engine/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Nyanners.dir/build.make CMakeFiles/Nyanners.dir/engine/main.cpp.o
.PHONY : engine/main.cpp.o

engine/main.i: engine/main.cpp.i
.PHONY : engine/main.i

# target to preprocess a source file
engine/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Nyanners.dir/build.make CMakeFiles/Nyanners.dir/engine/main.cpp.i
.PHONY : engine/main.cpp.i

engine/main.s: engine/main.cpp.s
.PHONY : engine/main.s

# target to generate assembly for a file
engine/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Nyanners.dir/build.make CMakeFiles/Nyanners.dir/engine/main.cpp.s
.PHONY : engine/main.cpp.s

vendor/imgui/imgui.o: vendor/imgui/imgui.cpp.o
.PHONY : vendor/imgui/imgui.o

# target to build an object file
vendor/imgui/imgui.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Nyanners.dir/build.make CMakeFiles/Nyanners.dir/vendor/imgui/imgui.cpp.o
.PHONY : vendor/imgui/imgui.cpp.o

vendor/imgui/imgui.i: vendor/imgui/imgui.cpp.i
.PHONY : vendor/imgui/imgui.i

# target to preprocess a source file
vendor/imgui/imgui.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Nyanners.dir/build.make CMakeFiles/Nyanners.dir/vendor/imgui/imgui.cpp.i
.PHONY : vendor/imgui/imgui.cpp.i

vendor/imgui/imgui.s: vendor/imgui/imgui.cpp.s
.PHONY : vendor/imgui/imgui.s

# target to generate assembly for a file
vendor/imgui/imgui.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Nyanners.dir/build.make CMakeFiles/Nyanners.dir/vendor/imgui/imgui.cpp.s
.PHONY : vendor/imgui/imgui.cpp.s

vendor/imgui/imgui_demo.o: vendor/imgui/imgui_demo.cpp.o
.PHONY : vendor/imgui/imgui_demo.o

# target to build an object file
vendor/imgui/imgui_demo.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Nyanners.dir/build.make CMakeFiles/Nyanners.dir/vendor/imgui/imgui_demo.cpp.o
.PHONY : vendor/imgui/imgui_demo.cpp.o

vendor/imgui/imgui_demo.i: vendor/imgui/imgui_demo.cpp.i
.PHONY : vendor/imgui/imgui_demo.i

# target to preprocess a source file
vendor/imgui/imgui_demo.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Nyanners.dir/build.make CMakeFiles/Nyanners.dir/vendor/imgui/imgui_demo.cpp.i
.PHONY : vendor/imgui/imgui_demo.cpp.i

vendor/imgui/imgui_demo.s: vendor/imgui/imgui_demo.cpp.s
.PHONY : vendor/imgui/imgui_demo.s

# target to generate assembly for a file
vendor/imgui/imgui_demo.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Nyanners.dir/build.make CMakeFiles/Nyanners.dir/vendor/imgui/imgui_demo.cpp.s
.PHONY : vendor/imgui/imgui_demo.cpp.s

vendor/imgui/imgui_draw.o: vendor/imgui/imgui_draw.cpp.o
.PHONY : vendor/imgui/imgui_draw.o

# target to build an object file
vendor/imgui/imgui_draw.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Nyanners.dir/build.make CMakeFiles/Nyanners.dir/vendor/imgui/imgui_draw.cpp.o
.PHONY : vendor/imgui/imgui_draw.cpp.o

vendor/imgui/imgui_draw.i: vendor/imgui/imgui_draw.cpp.i
.PHONY : vendor/imgui/imgui_draw.i

# target to preprocess a source file
vendor/imgui/imgui_draw.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Nyanners.dir/build.make CMakeFiles/Nyanners.dir/vendor/imgui/imgui_draw.cpp.i
.PHONY : vendor/imgui/imgui_draw.cpp.i

vendor/imgui/imgui_draw.s: vendor/imgui/imgui_draw.cpp.s
.PHONY : vendor/imgui/imgui_draw.s

# target to generate assembly for a file
vendor/imgui/imgui_draw.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Nyanners.dir/build.make CMakeFiles/Nyanners.dir/vendor/imgui/imgui_draw.cpp.s
.PHONY : vendor/imgui/imgui_draw.cpp.s

vendor/imgui/imgui_tables.o: vendor/imgui/imgui_tables.cpp.o
.PHONY : vendor/imgui/imgui_tables.o

# target to build an object file
vendor/imgui/imgui_tables.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Nyanners.dir/build.make CMakeFiles/Nyanners.dir/vendor/imgui/imgui_tables.cpp.o
.PHONY : vendor/imgui/imgui_tables.cpp.o

vendor/imgui/imgui_tables.i: vendor/imgui/imgui_tables.cpp.i
.PHONY : vendor/imgui/imgui_tables.i

# target to preprocess a source file
vendor/imgui/imgui_tables.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Nyanners.dir/build.make CMakeFiles/Nyanners.dir/vendor/imgui/imgui_tables.cpp.i
.PHONY : vendor/imgui/imgui_tables.cpp.i

vendor/imgui/imgui_tables.s: vendor/imgui/imgui_tables.cpp.s
.PHONY : vendor/imgui/imgui_tables.s

# target to generate assembly for a file
vendor/imgui/imgui_tables.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Nyanners.dir/build.make CMakeFiles/Nyanners.dir/vendor/imgui/imgui_tables.cpp.s
.PHONY : vendor/imgui/imgui_tables.cpp.s

vendor/imgui/imgui_widgets.o: vendor/imgui/imgui_widgets.cpp.o
.PHONY : vendor/imgui/imgui_widgets.o

# target to build an object file
vendor/imgui/imgui_widgets.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Nyanners.dir/build.make CMakeFiles/Nyanners.dir/vendor/imgui/imgui_widgets.cpp.o
.PHONY : vendor/imgui/imgui_widgets.cpp.o

vendor/imgui/imgui_widgets.i: vendor/imgui/imgui_widgets.cpp.i
.PHONY : vendor/imgui/imgui_widgets.i

# target to preprocess a source file
vendor/imgui/imgui_widgets.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Nyanners.dir/build.make CMakeFiles/Nyanners.dir/vendor/imgui/imgui_widgets.cpp.i
.PHONY : vendor/imgui/imgui_widgets.cpp.i

vendor/imgui/imgui_widgets.s: vendor/imgui/imgui_widgets.cpp.s
.PHONY : vendor/imgui/imgui_widgets.s

# target to generate assembly for a file
vendor/imgui/imgui_widgets.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Nyanners.dir/build.make CMakeFiles/Nyanners.dir/vendor/imgui/imgui_widgets.cpp.s
.PHONY : vendor/imgui/imgui_widgets.cpp.s

vendor/rlimgui/rlImGui.o: vendor/rlimgui/rlImGui.cpp.o
.PHONY : vendor/rlimgui/rlImGui.o

# target to build an object file
vendor/rlimgui/rlImGui.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Nyanners.dir/build.make CMakeFiles/Nyanners.dir/vendor/rlimgui/rlImGui.cpp.o
.PHONY : vendor/rlimgui/rlImGui.cpp.o

vendor/rlimgui/rlImGui.i: vendor/rlimgui/rlImGui.cpp.i
.PHONY : vendor/rlimgui/rlImGui.i

# target to preprocess a source file
vendor/rlimgui/rlImGui.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Nyanners.dir/build.make CMakeFiles/Nyanners.dir/vendor/rlimgui/rlImGui.cpp.i
.PHONY : vendor/rlimgui/rlImGui.cpp.i

vendor/rlimgui/rlImGui.s: vendor/rlimgui/rlImGui.cpp.s
.PHONY : vendor/rlimgui/rlImGui.s

# target to generate assembly for a file
vendor/rlimgui/rlImGui.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Nyanners.dir/build.make CMakeFiles/Nyanners.dir/vendor/rlimgui/rlImGui.cpp.s
.PHONY : vendor/rlimgui/rlImGui.cpp.s

vendor/tinyfiledialogs/tinyfiledialogs.o: vendor/tinyfiledialogs/tinyfiledialogs.c.o
.PHONY : vendor/tinyfiledialogs/tinyfiledialogs.o

# target to build an object file
vendor/tinyfiledialogs/tinyfiledialogs.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Nyanners.dir/build.make CMakeFiles/Nyanners.dir/vendor/tinyfiledialogs/tinyfiledialogs.c.o
.PHONY : vendor/tinyfiledialogs/tinyfiledialogs.c.o

vendor/tinyfiledialogs/tinyfiledialogs.i: vendor/tinyfiledialogs/tinyfiledialogs.c.i
.PHONY : vendor/tinyfiledialogs/tinyfiledialogs.i

# target to preprocess a source file
vendor/tinyfiledialogs/tinyfiledialogs.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Nyanners.dir/build.make CMakeFiles/Nyanners.dir/vendor/tinyfiledialogs/tinyfiledialogs.c.i
.PHONY : vendor/tinyfiledialogs/tinyfiledialogs.c.i

vendor/tinyfiledialogs/tinyfiledialogs.s: vendor/tinyfiledialogs/tinyfiledialogs.c.s
.PHONY : vendor/tinyfiledialogs/tinyfiledialogs.s

# target to generate assembly for a file
vendor/tinyfiledialogs/tinyfiledialogs.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Nyanners.dir/build.make CMakeFiles/Nyanners.dir/vendor/tinyfiledialogs/tinyfiledialogs.c.s
.PHONY : vendor/tinyfiledialogs/tinyfiledialogs.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... codegen"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... package"
	@echo "... package_source"
	@echo "... rebuild_cache"
	@echo "... update_mappings"
	@echo "... Luau.Analysis"
	@echo "... Luau.Analyze.CLI"
	@echo "... Luau.Ast"
	@echo "... Luau.Ast.CLI"
	@echo "... Luau.Bytecode.CLI"
	@echo "... Luau.CLI.Test"
	@echo "... Luau.CLI.lib"
	@echo "... Luau.CodeGen"
	@echo "... Luau.Common"
	@echo "... Luau.Compile.CLI"
	@echo "... Luau.Compiler"
	@echo "... Luau.Config"
	@echo "... Luau.Conformance"
	@echo "... Luau.EqSat"
	@echo "... Luau.Reduce.CLI"
	@echo "... Luau.Repl.CLI"
	@echo "... Luau.Require"
	@echo "... Luau.RequireNavigator"
	@echo "... Luau.UnitTest"
	@echo "... Luau.VM"
	@echo "... Nyanners"
	@echo "... glfw"
	@echo "... isocline"
	@echo "... raylib"
	@echo "... engine/instances/DataModel.o"
	@echo "... engine/instances/DataModel.i"
	@echo "... engine/instances/DataModel.s"
	@echo "... engine/instances/Instance.o"
	@echo "... engine/instances/Instance.i"
	@echo "... engine/instances/Instance.s"
	@echo "... engine/instances/Script.o"
	@echo "... engine/instances/Script.i"
	@echo "... engine/instances/Script.s"
	@echo "... engine/lua/system.o"
	@echo "... engine/lua/system.i"
	@echo "... engine/lua/system.s"
	@echo "... engine/lua/utils.o"
	@echo "... engine/lua/utils.i"
	@echo "... engine/lua/utils.s"
	@echo "... engine/main.o"
	@echo "... engine/main.i"
	@echo "... engine/main.s"
	@echo "... vendor/imgui/imgui.o"
	@echo "... vendor/imgui/imgui.i"
	@echo "... vendor/imgui/imgui.s"
	@echo "... vendor/imgui/imgui_demo.o"
	@echo "... vendor/imgui/imgui_demo.i"
	@echo "... vendor/imgui/imgui_demo.s"
	@echo "... vendor/imgui/imgui_draw.o"
	@echo "... vendor/imgui/imgui_draw.i"
	@echo "... vendor/imgui/imgui_draw.s"
	@echo "... vendor/imgui/imgui_tables.o"
	@echo "... vendor/imgui/imgui_tables.i"
	@echo "... vendor/imgui/imgui_tables.s"
	@echo "... vendor/imgui/imgui_widgets.o"
	@echo "... vendor/imgui/imgui_widgets.i"
	@echo "... vendor/imgui/imgui_widgets.s"
	@echo "... vendor/rlimgui/rlImGui.o"
	@echo "... vendor/rlimgui/rlImGui.i"
	@echo "... vendor/rlimgui/rlImGui.s"
	@echo "... vendor/tinyfiledialogs/tinyfiledialogs.o"
	@echo "... vendor/tinyfiledialogs/tinyfiledialogs.i"
	@echo "... vendor/tinyfiledialogs/tinyfiledialogs.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

